<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="DbModels.fs" />
    <Compile Include="Db.fs" />
    <Compile Include="Repositories/Channels.fs" />
    <Compile Include="Repositories/Rps.fs" />
    <Compile Include="Repositories/Users.fs" />
    <Compile Include="Repositories/NewsFeeds.fs" />
    <Compile Include="Repositories/Aliases.fs" />
    <Compile Include="Repositories/Reminders.fs" />
    <Compile Include="Migration.fs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="./Migrations/*.sql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Chatbot.Common/Chatbot.Common.fsproj" />
    <ProjectReference Include="../Chatbot.Core/Chatbot.Core.fsproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper.FSharp" Version="4.9.0" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.0" />
  </ItemGroup>

</Project>