services:
  chatbot:
    image: chatbot:latest
    platform: linux/arm/v7
    networks:
      - private_network
    env_file:
      - .env
    volumes:
      - chatbot_data:/app/data

networks:
  private_network:
    driver: bridge

volumes:
  chatbot_data:
    external: true