services:
  chatbot:
    image: chatbot
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - configuration=Debug
    networks:
      - private_network
    env_file:
      - .env
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
      - data/chat.db:/app/data/chat.db

networks:
  private_network:
    driver: bridge