services:
  chatbot:
    image: chatbot:latest
    platform: linux/arm/v7
    volumes:
      - chatbot_data:/app/data
    env_file:
      - ./.env

    networks:
      - private_network

networks:
  private_network:
    driver: bridge

volumes:
  chatbot_data:
    external: true