<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Alias.fs" />
    <Compile Include="Logs.fs" />
    <Compile Include="Help.fs" />
    <Compile Include="Nasa.fs" />
    <Compile Include="UrbanDictionary.fs" />
    <Compile Include="Wikipedia.fs" />
    <Compile Include="News.fs" />
    <Compile Include="Weather.fs" />
    <Compile Include="FaceIt.fs" />
    <Compile Include="Reddit.fs" />
    <Compile Include="RiotGames.fs" />
    <Compile Include="Trivia.fs" />
    <Compile Include="Braille.fs" />
    <Compile Include="TextTransform.fs" />
    <Compile Include="RandomClip.fs" />
    <Compile Include="Channel.fs" />
    <Compile Include="Stream.fs" />
    <Compile Include="UserChatColor.fs" />
    <Compile Include="UserId.fs" />
    <Compile Include="LeaveChannel.fs" />
    <Compile Include="JoinChannel.fs" />
    <Compile Include="CatFact.fs" />
    <Compile Include="Calculator.fs" />
    <Compile Include="EightBall.fs" />
    <Compile Include="RockPaperScissors.fs" />
    <Compile Include="CoinFlip.fs" />
    <Compile Include="Chance.fs" />
    <Compile Include="Roll.fs" />
    <Compile Include="Ping.fs" />
    <Compile Include="Time.fs" />
    <Compile Include="Vod.fs" />
    <Compile Include="Echo.fs" />
    <Compile Include="xd.fs" />
    <Compile Include="Emotes.fs" />
    <Compile Include="Pick.fs" />
    <Compile Include="Encode.fs" />
    <Compile Include="TopStreams.fs" />
    <Compile Include="AddBetween.fs" />
    <Compile Include="Remind.fs" />
    <Compile Include="AccountAge.fs" />
    <Compile Include="SubAge.fs" />
    <Compile Include="FollowAge.fs" />
    <Compile Include="Fill.fs" />
    <Compile Include="Slots.fs" />
    <Compile Include="Gpt.fs" />
    <Compile Include="GptImage.fs" />
    <Compile Include="ChatSummary.fs" />
    <Compile Include="ProfilePicture.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FParsec" Version="2.0.0-beta2" />
    <PackageReference Include="FsToolkit.ErrorHandling" Version="5.1.0" />
    <PackageReference Include="SkiaSharp" Version="3.119.1" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="3.119.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Chatbot.Core\Chatbot.Core.fsproj" />
    <ProjectReference Include="..\Chatbot.Common\Chatbot.Common.fsproj" />
  </ItemGroup>

</Project>